name: CI/CD for HTML Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t your-dockerhub-username/html-project:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push your-dockerhub-username/html-project:latest
