name: CI/CD for HTML Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t samrachdx/html-project:latest .
          docker login -u samrachdx -p ${{ secrets.HTML_PROJECT }}
          docker push samrachdx/html-project:latest
